<?php

/**
 * This is the model base class for the table "{{auth_item_child}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AuthItemChild".
 *
 * Columns in table "{{auth_item_child}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $parent
 * @property string $child
 *
 */
abstract class BaseAuthItemChild extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{auth_item_child}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AuthItemChild|AuthItemchildren', $n);
	}

	public static function representingColumn() {
		return 'parent';
	}

	public function rules() {
		return array(
			array('parent, child', 'required'),
			array('parent, child', 'length', 'max'=>64),
			array('parent, child', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'parent' => Yii::t('app', 'Parent'),
			'child' => Yii::t('app', 'Child'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('parent', $this->parent, true);
		$criteria->compare('child', $this->child, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}